In [1]:
import numpy as np

In [5]:
a1 = np.array ([1,2,3])
a1

array([1, 2, 3])

In [7]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a1.ndim

1

In [9]:
a2.ndim

2

In [13]:
a3=np.array([[[1,2,3],[4,5,6]],
           [[7,8,9],[10,11,12]],
           [[13,14,15],[16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [14]:
a3.ndim

3

In [22]:
a3.ndim, a3.shape, a3.size, a3.dtype

(3, (3, 2, 3), 18, dtype('int32'))

In [23]:
a2.ndim, a2.shape, a2.size, a2.dtype

(2, (2, 3), 6, dtype('int32'))

In [24]:
a1.ndim, a1.shape, a1.size, a1.dtype

(1, (3,), 3, dtype('int32'))

In [27]:
import pandas as df

In [30]:
df1 = df.DataFrame(a1)
df1

0
0  1
1  2
2  3

In [31]:
df2 = df.DataFrame(a2)
df2

0  1  2
0  1  2  3
1  4  5  6

In [32]:
df3 = df.DataFrame(a3)
df3

ValueError: Must pass 2-d input. shape=(3, 2, 3)

In [36]:
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
a4 = np.arange(0,100,3)
a4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [47]:
random_array= np.random.randint(0,10, size= (7,2))
random_array

array([[3, 5],
       [5, 5],
       [7, 0],
       [7, 9],
       [9, 1],
       [4, 1],
       [0, 1]])

In [50]:
random_array= np.random.random( (3,5))
random_array

array([[0.40454166, 0.39892725, 0.78678304, 0.72346101, 0.3809591 ],
       [0.44248981, 0.5960809 , 0.92863213, 0.99788124, 0.35399158],
       [0.28351551, 0.3919298 , 0.87359977, 0.04091086, 0.7697332 ]])

In [54]:
np.random.seed(seed=42)
random_array_2= np.random.randint(0,10, size= (4,6))
random_array_2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [55]:
random_array_3= np.random.randint(1,10, size= (3,7))
random_array_3

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [57]:
unique_array = np.unique(random_array_3)
unique_array

array([1, 2, 3, 4, 5, 7, 9])

In [58]:
unique_array[0]

1

In [62]:
random_array_3[1:,1:]

array([[3, 7, 5, 9, 7, 2],
       [9, 2, 9, 5, 2, 4]])

In [67]:
R1= np.random.randint(0,10, size= (3,5))
R1

array([[9, 1, 9, 3, 7],
       [6, 8, 7, 4, 1],
       [4, 7, 9, 8, 8]])

In [69]:
R2 =np.ones((3,5))
R2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
R3=R1+R2
R3


array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [72]:
R4 =np.ones((5,3))
R4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
R5= R3+R4.T
R5

array([[11.,  3., 11.,  5.,  9.],
       [ 8., 10.,  9.,  6.,  3.],
       [ 6.,  9., 11., 10., 10.]])

In [76]:
R2 =np.ones((3,5))
R2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [80]:
R6= R5-R2
R6

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [82]:
R7 = R2 * R6
R7

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [84]:
R8 = R7 **2
R8

array([[100.,   4., 100.,  16.,  64.],
       [ 49.,  81.,  64.,  25.,   4.],
       [ 25.,  64., 100.,  81.,  81.]])

In [86]:
R9 = np.square(R7)
R9

array([[100.,   4., 100.,  16.,  64.],
       [ 49.,  81.,  64.,  25.,   4.],
       [ 25.,  64., 100.,  81.,  81.]])

In [88]:
mean = np.mean(R9)
mean

57.2

In [91]:
maximum = np.max(R9)
maximum

100.0

In [92]:
minimum = np.min(R9)
minimum

4.0

In [95]:
standard_deviation = np.std ((R9))
standard_deviation

33.49865668948533

In [97]:
variance = np.var(R9)
variance

1122.16

In [100]:
R9_new = R9.reshape(3,5,1)
R9_new

array([[[100.],
        [  4.],
        [100.],
        [ 16.],
        [ 64.]],

       [[ 49.],
        [ 81.],
        [ 64.],
        [ 25.],
        [  4.]],

       [[ 25.],
        [ 64.],
        [100.],
        [ 81.],
        [ 81.]]])

In [101]:
R9_new.T

array([[[100.,  49.,  25.],
        [  4.,  81.,  64.],
        [100.,  64., 100.],
        [ 16.,  25.,  81.],
        [ 64.,   4.,  81.]]])

In [104]:
np.random.seed(0)
mat1 = np.random.randint(10, size = (5,3))
mat2 = np.random.randint(10, size = (5,3))

In [105]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [106]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [107]:
mat1 > mat2

array([[False, False, False],
       [False,  True,  True],
       [False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [108]:
mat1 >= mat2

array([[False, False, False],
       [False,  True,  True],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [109]:
mat1 > 7

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [ True,  True, False]])

In [110]:
mat1 == mat2

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False]])

In [111]:
np.sort(mat1)

array([[0, 3, 5],
       [3, 7, 9],
       [2, 3, 5],
       [4, 6, 7],
       [1, 8, 8]])

In [112]:
np.argsort(mat1)

array([[1, 2, 0],
       [0, 1, 2],
       [2, 0, 1],
       [0, 2, 1],
       [2, 0, 1]], dtype=int64)

In [113]:
mat1.max()

9

In [114]:
mat1.min()

0

In [119]:
np.argmax(mat1, axis = 1)

array([0, 2, 1, 1, 0], dtype=int64)

In [120]:
np.argmin(mat1, axis = 0)

array([1, 0, 4], dtype=int64)

In [121]:
np.random.randn(3,5)

array([[ 0.59124281, -0.7827755 , -0.44423283, -0.34518616, -0.88180055],
       [-0.44265324, -0.5409163 , -1.32322737, -0.11279892,  0.90734594],
       [ 0.81526991,  0.22909795, -1.02617878,  0.47752547,  1.29269823]])

In [123]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])